### ISSUE TITLE
Feature Request: open sqlite database by default if it is specified in ARGV

### ISSUE THREAD

**Issue by basiliscos** [kuerbis/App-DBBrowser#4]
Hello! 

Thanks for the good application, again!

I noted on my self, that I always launch the application via:

```bash
$ db-browser /tmp/wookie-test.db
```

So, I always specify the full path to sqlite database. App-DBBrowser is clever enough to detect, that I try to use sqlite, but I have to type additional keystrokes (select my database via arrays and choose it via enter). 

It would be nice if the specified database will be already selected if I specified full path to it.

WBR, basiliscos.

**Comment by kuerbis** [comment]
You can know pass the database name as an argument even when SQLite is in use.

**Comment by kuerbis** [comment]
Now a database is selected automatically if only one database is available.
